language: generic
git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$HOME/.ghc"

python: 3.7
env: BUILD=stack ARGS="--resolver lts-13.15"
jobs:
  include:
  - os: linux
    compiler: ": #stack 8.6.4"

  - os: osx
    osx_image: xcode12
    compiler: ": #stack 8.6.4 osx"
 
  - os: osx
    osx_image: xcode11
    compiler: ": #stack 8.6.4 osx"
   
  - os: osx
    osx_image: xcode10
    compiler: ": #stack 8.6.4 osx"


before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# We want to always allow newer versions of packages when building on GHC HEAD
- CABALARGS=""
- if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi

# Download and unpack the stack executable
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
  # Use the more reliable S3 mirror of Hackage
  mkdir -p $HOME/.cabal
  echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
  echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config

script:
- |
  set -ex
  stack --no-terminal build
  stack --no-terminal install
  set +ex

notifications:
  email: false

before_deploy:
  - source build-release.sh

deploy:
  provider: releases
  api_key: $GH_TK
  file: $ZIP_FILE
  draft: true
  on:
    branch: cfg

after_deploy:
  - echo "Release Deployed"
