name:                RBNF
version:             0.1.0.0
github:              "thautwarm/RBNF"
license:             BSD3
author:              "thautwarm"
maintainer:          "twshere@outlook.com"
copyright:           "2020 thautwarm"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thautwarm/RBNF#readme>

default-extensions:
- ViewPatterns
- DeriveGeneric
- DeriveFunctor
- DeriveTraversable
- LambdaCase
- TemplateHaskell
- DuplicateRecordFields
- StandaloneDeriving
- ExistentialQuantification
- MultiParamTypeClasses
- NamedFieldPuns
- PartialTypeSignatures
- FlexibleInstances

when:
  - condition: os(darwin)
    then:
      ghc-options: -Wall -O2
      ld-options:
      - -pthread
      - -Wall
    else:
      ghc-options: -Wall -O2
      ld-options:
      - -pthread
      - -Wall
      # FIXME: some linux distros cannot statically link libgmp
      # ghc-options: -Wall -O2 -static
      # cc-options: -static
      # ld-options:
      # - -static
      # - -pthread
      # - -Wall

dependencies:
- base >= 4.7 && < 5
- mtl
- text
- containers
- lens
- vector
- aeson
- transformers
- prettyprinter
- utf8-string
- parsec
library:
  source-dirs:
  - src

ghc-options:
  - -fno-warn-partial-type-signatures
  - -Wall
  - -Wno-name-shadowing
executables:
  fff-pgen:
    main:                Main.hs
    source-dirs:         pgen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RBNF
    - base >=4.7 && <5
  fff-lex:
    main:                Main.hs
    source-dirs:         lex
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RBNF
    - base >=4.7 && <5
